#!/usr/bin/env node
/**
 * sync-agents.js
 *
 * 把 CLAUDE.md 同步到 AGENTS.md。CLAUDE.md 是 canonical source,AGENTS.md 派生。
 * 替换规则：
 *   - 标题 "team-standards 插件开发规范" 保持
 *   - 正文中 "Claude" → "Codex"(限于触发表前导句等少数语境，不替换 "Claude Code" 之类专有名词)
 *   - 顶部加入 auto-generated 标记
 *
 * 用法:
 *   node scripts/sync-agents.js              # 同步
 *   node scripts/sync-agents.js --check      # 仅校验(CI 用),不一致 exit 1
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'CLAUDE.md');
const DST = path.join(ROOT, 'AGENTS.md');

const AUTO_HEADER = [
  '<!--',
  'AUTO-GENERATED FROM CLAUDE.md by scripts/sync-agents.js',
  'DO NOT EDIT THIS FILE DIRECTLY. EDIT CLAUDE.md AND RUN:',
  '    node scripts/sync-agents.js',
  '-->',
  '',
].join('\n');

function transform(claudeContent) {
  // 1. 把"Claude 在以下场景"等用语切换为 Codex
  //    只替换"Claude 在"、"Claude 必须"、"Claude Code 中"等明确指代 agent 的处,
  //    不动 "Claude Code"(产品名)出现在安装步骤等地方
  let out = claudeContent
    .replace(/^# team-standards 插件开发规范$/m, '# team-standards 插件开发规范（Codex 入口）')
    .replace(/\*\*Skill 必须主动触发，不等用户显式调用。\*\* Claude 在以下场景/g,
             '**Skill 必须主动触发，不等用户显式调用。** Codex 在以下场景')
    .replace(/Claude 在以下场景必须自动识别/g, 'Codex 在以下场景必须自动识别')
    .replace(/若 Claude 即将对源码文件/g, '若 Codex 即将对源码文件');

  return AUTO_HEADER + out;
}

function readFile(p) {
  return fs.readFileSync(p, 'utf8');
}

function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');

  if (!fs.existsSync(SRC)) {
    console.error(`[sync-agents] missing source: ${SRC}`);
    process.exit(2);
  }

  const claude = readFile(SRC);
  const expected = transform(claude);

  if (checkOnly) {
    if (!fs.existsSync(DST)) {
      console.error(`[sync-agents] AGENTS.md missing; run: node scripts/sync-agents.js`);
      process.exit(1);
    }
    const actual = readFile(DST);
    if (actual !== expected) {
      console.error(`[sync-agents] AGENTS.md is out of sync with CLAUDE.md`);
      console.error(`  fix:  node scripts/sync-agents.js`);
      process.exit(1);
    }
    console.log('[sync-agents] AGENTS.md is up-to-date.');
    return;
  }

  fs.writeFileSync(DST, expected);
  console.log(`[sync-agents] wrote ${path.relative(ROOT, DST)} (${expected.length} bytes)`);
}

main();
